baseURL = "https://visda.vec.ac.nz"
title = "VISDA"
author = "Victoria Engineering Club"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  mainSections = ['blog']

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "VEC Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "VEC"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fa5 = true

  [params.homepage_meta_tags]
    meta_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_og_title = "VEC"
    meta_og_type = "website"
    meta_og_url = "https://visda.vec.ac.nz"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Victoria Engineering Club"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 2
  
  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events/"
    weight = 3

  [[menu.main]]
    identifier = "board"
    name = "Board"
    url = "/board/"
    weight = 4

  [[menu.main]]
    identifier = "Collective"
    name = "Collective"
    url = "/collective/"
    weight = 5

  [[menu.main]]
    identifier = "meetings"
    name = "Meetings"
    url = "/meetings/"
    weight = 6
  
  [[menu.main]]
    identifier = "register"
    name = "Register"
    url = "https://vuw.qualtrics.com/jfe/form/SV_6D2hjJlY8Hu0hqm?fbclid=IwAR0gSbuVxU-hluLO6WHialiBAA8XTC38SMsovv7a2TSiQfE2yuGNzSj2qYs"
    weight = 7

  # Footer Menu

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/vecnz"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 1
